export default function phoneData() {
  return {
    US: { country: "United States", countryCode: "1" },
    CA: { country: "Canada", countryCode: "1" },
    GB: { country: "United Kingdom", countryCode: "44" },
    AU: { country: "Australia", countryCode: "61" },
    AT: { country: "Austria", countryCode: "43" },
    BS: { country: "Bahamas", countryCode: "1" },
    BR: { country: "Brazil", countryCode: "55" },
    BG: { country: "Bulgaria", countryCode: "359" },
    CN: { country: "China", countryCode: "86" },
    DK: { country: "Denmark", countryCode: "45" },
    FI: { country: "Finland", countryCode: "358" },
    FR: { country: "France", countryCode: "33" },
    DE: { country: "Germany", countryCode: "49" },
    HK: { country: "Hong Kong", countryCode: "852" },
    IN: { country: "India", countryCode: "91" },
    IE: { country: "Ireland", countryCode: "353" },
    IL: { country: "Israel", countryCode: "972" },
    IT: { country: "Italy", countryCode: "39" },
    JP: { country: "Japan", countryCode: "81" },
    LI: { country: "Lichtenstein", countryCode: "423" },
    LT: { country: "Lithuania", countryCode: "370" },
    MX: { country: "Mexico", countryCode: "52" },
    NL: { country: "Netherlands", countryCode: "31" },
    NZ: { country: "New Zealand", countryCode: "64" },
    RO: { country: "Romania", countryCode: "40" },
    SG: { country: "Singapore", countryCode: "65" },
    ZA: { country: "South Africa", countryCode: "27" },
    KR: { country: "South Korea", countryCode: "82" },
    SE: { country: "Sweden", countryCode: "46" },
    CH: { country: "Switzerland", countryCode: "41" },
    TH: { country: "Thailand", countryCode: "66" },
    AE: { country: "United Arab Emirates", countryCode: "971" },
    ES: { country: "Spain", countryCode: "34" },
  };
}
